### ISSUE TITLE
Incompatible with Charm

### ISSUE THREAD

**Issue by SplendidAlakey** [CammiesCorner/The-Box-Trot#1]
**MC** 1.18.2
**Fabric API** 0.48.0
**TheBoxTrot** 1.1
**[Charm](https://www.curseforge.com/minecraft/mc-mods/charm)** 4.0.0

When both mods are present, the game will crash on init.

Logs: https://gist.github.com/Footage2-Amply-Pounce/c3793bc221b67063a8cfbe93b1b3cb9c

My Charm config in case it's relevant: https://gist.github.com/Footage2-Amply-Pounce/1558186d650c4d1f908f36dffddb873b

**Comment by CammiePone** [comment]
So, due to how Charm is structured, it's quite literally impossible for me to diagnose which of their mixins broke it, but it's almost certainly a Charm problem. Go poke them about it.
