### ISSUE TITLE
Bug: Players can use items/weapons when sneaking with the barrel on.

### ISSUE THREAD

**Issue by arazadaz** [CammiesCorner/The-Box-Trot#10]
As the title suggest, players can use weapons while sneaking with a barrel on their head. The issue with this, is that mobs ignore the player when they have a box on their head. This means players cheese mobs without fear of being attacked just by sneaking with a barrel on. The fix to this would to either be to prevent players from using items/weapons while as a box or allow mobs to maintain aggro once they've targeted the player. A combination of the 2 would be best.

**Comment by CammiePone** [comment]
it's meant to do that, tbh. the mod is just a silly thing I made in a day because I loved the feature in the snapshots. it's not meant to be used in a serious capacity ^^;

**Comment by arazadaz** [comment]
I see. Would you mind me making a port that does what I suggested then?
