### ISSUE TITLE
Abuse. Crouching makes you invisible and invincible, even during attack. Please add config to turn it off

### ISSUE THREAD

**Issue by yetbad** [CammiesCorner/The-Box-Trot#11]
Abuse. Crouching makes you invisible and invincible, even during attack. Could you please add config to turn it off, it makes it really easy to abuse

**Comment by CammiePone** [comment]
this isn't a mod to be used seriously, my dude. it's literally a mod that adds a feature from an april fools snapshot

**Comment by yetbad** [comment]
Still great mod for social interactions on server 👯
