### ISSUE TITLE
Crash report! What's causing this?

### ISSUE THREAD

**Issue by JumpStartFartHam** [CammiesCorner/The-Box-Trot#6]
I'm making a modpack and having trouble discerning what's interfering with The Box Trot and causing the game not to launch. Any idea? I'm on Fabric loader 0.14.9. Here's the latest log from the crash.

[latest.log](https://github.com/CammiePone/The-Box-Trot/files/9375813/latest.log)

**Comment by CammiePone** [comment]
fantastic question. I'm not entirely certain why it's crashing. it's definitely related to Mixin Extras'  `@WrapWithCondition`, but idk what exactly is causing it to crash :/

best bet is to just try removing mods and seeing if you can find out if it's a mod that's causing this, and which one. I could probably help more knowing that information

**Comment by JumpStartFartHam** [comment]
Hmm, alright, I'll do some experimenting and see what I can find out - I'm thinking it's probably some sort of other mod because Box Trot works just fine when I install it by itself, but who knows. Thank you for the input! I'll update here if I can find out what's causing it.

**Comment by JumpStartFartHam** [comment]
Okay! So as best as I can tell, it looks like the culprit is the Charm mod, version 4.2.1. I'm not sure what exactly is causing it - I thought it was the variant barrels option, but that doesn't seem to be it as disabling that module still causes it to crash. Regardless, the incompatibility seems to come from having both Charm and The Box Trot installed at the same time.

Thanks for your help! Also love the mod!

**Comment by CammiePone** [comment]
yeah that makes sense. Charm causes crashes with a ton of mods, and I guess it fucks with Mixin Extras too
