### ISSUE TITLE
Incompatibility with Better Combat

### ISSUE THREAD

**Issue by JumpStartFartHam** [CammiesCorner/The-Box-Trot#7]
Just noting this here for the dev's reference! There's a compatibility issue where using the Better Combat mod causes the player's head to still be visible while wearing a barrel. I presume this is likely on Better Combat's side since it makes some changes to player animations, though it's odd that this occurs even when not attacking. I thought it might be helpful to be aware of the issue for the sake of noting incompatibilities with other mods unless/until a patch is made for Better Combat that fixes it.

For reference, this is Minecraft 1.19, Fabric v 0.14.9, Box Trot v 1.4, and Better Combat v 1.0.13.

![2022-08-19_11 03 09](https://user-images.githubusercontent.com/70125767/185661808-88997517-4ced-47dd-b0f3-281325b49da9.png)

![2022-08-19_11 03 21](https://user-images.githubusercontent.com/70125767/185661858-652b0360-2bb3-4040-9a61-507733147f13.png)

**Comment by JumpStartFartHam** [comment]
Just a quick update, this got patched in v 1.1.0 of Better Combat - problem solved!

**Comment by CammiePone** [comment]
pog!
