### ISSUE TITLE
Body disappears with FirstPersonModel mod

### ISSUE THREAD

**Issue by slava110** [CammiesCorner/The-Box-Trot#8]
First Person Model mod body isn't visible when wearing a barrel
![image](https://user-images.githubusercontent.com/26705162/200001850-5e01256f-0ef5-480e-9cfc-c764746a57a4.png)
(with F1)
![image](https://user-images.githubusercontent.com/26705162/200001913-0c57c3e5-7da6-4c23-9090-4093485407e4.png)
Mod link: https://modrinth.com/mod/first-person-model
ModLoader: Quilt 0.17.6
The Box Trot: 1.4
FirstPersonModel: 2.2.0

**Comment by slava110** [comment]
As this is mod conflict issue I'm linking issue in another mod's GitHub issue so you will be able to talk about this issue:
https://github.com/tr7zw/FirstPersonModel/issues/307

**Comment by CammiePone** [comment]
that's because it's an overlay, and the first person player models mod turns those off

**Comment by tr7zw** [comment]
I don't turn them off, I just render the player like in f5. The only way to "fix" this would be to use the built in API to auto disable the firstperson mod while this mod is active(https://github.com/tr7zw/FirstPersonModel/blob/1.19/FPFabric/src/main/java/dev/tr7zw/firstperson/fabric/modsupport/FreecamSupport.java example). Also just now understood what the bug request is in the first place, that this overlay is not there. I thought it was about somehow showing the legs while you're inside the box, which doesn't make any sense.

**Comment by slava110** [comment]
@tr7zw, the issue *isn't about overlay*. I thought I stated it clearly - the issue is that body isn't rendered while you're wearing a barrel. **F1 view** here is just so you can clearly see that body **isn't there**. Only legs and arms are visible, floating in the air without body part.
Possible fixes for this problem:
- Disable FPM if player is wearing a barrel
- Find out why body isn't rendered and force render it
- Render the whole barrel model instead of simple overlay (would be awesome, ngl)

That's why I asked about rendering custom model over player without conflicting with FPM rendering. I want to try to implement last fix, rendering the whole barrel model instead of on-screen overlay

**Comment by tr7zw** [comment]
Option 2 and 3 are not possible/incorrect. So the only real option is to just-auto toggle the mod for the time and use this mods rendering.
